name = "brook-queuemanager"
type = "javascript"
main = "worker/src/index.ts"
compatibility_date = "2026-01-01"

[assets]
directory = "./web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[build]
command = "cd web && bun install && bun run build"

[vars]
ZOOM_ACCOUNT_ID = "HSo9AYLTQ-mxFMUQg3hn7w"
ZOOM_CLIENT_ID = "pUWJUWf1SlypIAQZ83Gm8A"